#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap          3.5
bspc config left_padding                2
bspc config right_padding                2
bspc config bottom_padding                2
bspc config top_padding                26
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#WALLPAPER
feh --bg-fill ~/Pictures/wallpaper.png

# POLYBAR
~/.config/polybar/launch.sh
