[colors.bright]
black = "#002b36" # base03
red = "#cb4b16" # orange
green = "#586e75" # base01
yellow = "#657b83" # base00
blue = "#839496" # base0
magenta = "#6c71c4" # violet
cyan = "#93a1a1" # base1
white = "#fdf6e3" # base3

[colors.cursor]
cursor = "#839496"

[colors.normal]
black = "#073642" # base02
red = "#dc322f" # red
green = "#859900" # green
yellow = "#b58900" # yellow
blue = "#268bd2" # blue
magenta = "#d33682" # magenta
cyan = "#2aa198" # cyan
white = "#eee8d5" # base2

[colors.primary]
background = "#002b36" 
foreground = "#839496"

[cursor]
style = "Underline"
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 6

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ClearHistory"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[hints]

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse = { mods = "Control", enabled = true }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


[scrolling]
history = 100000

[window]
startup_mode = "Maximized"
dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 88
lines = 23

[window.padding]
x = 10
y = 10